# Generated by Django 5.2.5 on 2025-11-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_name', models.CharField(max_length=100)),
                ('ayah_number', models.IntegerField()),
                ('arabic', models.TextField()),
                ('english', models.TextField()),
                ('urdu', models.TextField()),
                ('word_by_word', models.TextField()),
                ('tafsir_text', models.TextField()),
                ('tafsir_video_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
