# Generated by Django 5.2.5 on 2025-11-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verse',
            name='word_by_word',
        ),
        migrations.AlterField(
            model_name='verse',
            name='tafsir_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
