"""
Django settings for islamic_backend project.
Generated by 'django-admin startproject' using Django 5.2.5.
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================================================================
# CORE SETTINGS
# ==============================================================================

# Use environment variable for SECRET_KEY in production, with a default for local development
SECRET_KEY = os.environ.get(
    'SECRET_KEY', 
    default='django-insecure-^j!(==#3g_z$==u5)#pqdq_k9qajr38@6z8m3trkwy-t2#p*#5'
)

# DEBUG is True in local development, but will be False on Render
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# ALLOWED_HOSTS will be automatically configured for Render
ALLOWED_HOSTS = []
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
else:
    # For local development, allows connection from emulator and local machine
    ALLOWED_HOSTS.extend(['localhost', '127.0.0.1', '10.0.2.2'])


# ==============================================================================
# APPLICATION DEFINITION
# ==============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic', # For serving static files in development

    # Your Apps
    'quran',
    
    # 3rd Party Apps
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Should be right after SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # For allowing Flutter app to connect
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'islamic_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'islamic_backend.wsgi.application'


# ==============================================================================
# DATABASE CONFIGURATION
# ==============================================================================

# Use local PostgreSQL for development, and Render's DATABASE_URL for production
DATABASES = {
    'default': dj_database_url.config(
        default='postgres://postgres:dAtAbAsE411@localhost:5432/islamic_db',
        conn_max_age=600
    )
}


# ==============================================================================
# PASSWORD VALIDATION, I18N, AND OTHER SETTINGS
# ==============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==============================================================================
# CORS (FOR FLUTTER APP CONNECTION)
# ==============================================================================

CORS_ALLOW_ALL_ORIGINS = True # Allows your Flutter app to connect from any origin.


# ==============================================================================
# STATIC FILES (FOR RENDER DEPLOYMENT)
# ==============================================================================

STATIC_URL = '/static/'

# This setting is only used in production (on Render)
if not DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
